version: '3.8'

services:
  php:
    image: cleivo/comercialrecanto:prod
    container_name: comercial_php
    restart: always
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"

      # Router HTTPS
      - "traefik.http.routers.comercial.rule=Host(`comercial.recantosocial.com.br`)"
      - "traefik.http.routers.comercial.entrypoints=websecure"
      - "traefik.http.routers.comercial.tls.certresolver=le"

      # Service
      - "traefik.http.services.comercial.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
